app:
  name: "backend"
  port: ":8080"

database:
  dsn: "root:hhh2021...@tcp(127.0.0.1:3306)/tokove?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conns: 10
  max_open_conns: 100

redis:
  addr: "127.0.0.1:6379"
  db: 0
  password: ""

jwt:
  secret: "your_secret_key"    # JWT 密钥
  expire_hours: 168            # 过期时间，单位小时（7天 = 168小时）
